version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: streamforge-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: streamforge
      POSTGRES_PASSWORD: streamforge
      POSTGRES_DB: streamforge_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
